name: WSA with GApps
on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architecture (arm64 or x64)'
        required: true
        default: 'arm64'
      android:
        description: 'Android version (13 or 14)'
        required: true
        default: '14'
      variant:
        description: 'gapps or nogapps'
        required: true
        default: 'gapps'
      root:
        description: 'none or magisk'
        required: true
        default: 'none'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full unzip lzip tar wget

      - name: Prepare folders
        run: |
          mkdir -p IMAGES GAPPS output

      - name: Download WSA msixbundle
        run: |
          wget -O IMAGES/WSA.msixbundle \
            "https://store.rg-adguard.net/api/GetFiles?rid=9P3395VX91NR&ring=Retail&lang=en-US&dl=1"

      - name: Download MindTheGapps
        run: |
          wget -L -O GAPPS/mindthegapps.zip \
            "https://github.com/MindTheGapps/14.0.0-arm64/releases/download/MindTheGapps-14.0.0-arm64-20250203_200051/MindTheGapps-14.0.0-arm64-20250203_200051.zip"

      - name: Make local scripts executable
        run: |
          chmod +x ./*.sh ./misc/*.sh

      - name: Extract GApps
        run: |
          sudo bash extract_gapps_pico.sh

      - name: Extend and mount images
        run: |
          sudo bash extend_and_mount_images.sh

      - name: Apply GApps
        run: |
          sudo bash apply.sh

      - name: Unmount images
        run: |
          sudo bash unmount_images.sh

      - name: Package results
        run: |
          7z a output/WSA-with-GApps-${{ github.run_id }}.7z IMAGES GAPPS

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WSA-with-GApps
          path: output/*.7z
